import smtplib
import asyncio
from email.message import EmailMessage
import os
from dotenv import load_dotenv

load_dotenv()

SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
SMTP_HOST = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))

async def _get_html_template(title: str, message: str, task_text: str = None):
    """
    Generates a premium, dark-mode HTML template for InnerSync AI.
    """
    task_section = ""
    if task_text:
        task_section = f"""
        <div style="background: rgba(255, 255, 255, 0.05); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 16px; padding: 20px; margin: 20px 0;">
            <p style="color: #94a3b8; font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 0.2em; margin: 0 0 10px 0;">Identified Blockage</p>
            <p style="color: #ffffff; font-size: 16px; font-weight: 600; margin: 0;">{task_text}</p>
        </div>
        """

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" rel="stylesheet">
        <style>
            body {{ margin: 0; padding: 0; background-color: #09090b; font-family: 'Inter', Arial, sans-serif; -webkit-font-smoothing: antialiased; }}
            .container {{ max-width: 600px; margin: 40px auto; background: #000000; border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 32px; overflow: hidden; box-shadow: 0 20px 50px rgba(0,0,0,0.5); }}
            .header {{ background: linear-gradient(135deg, #06b6d4 0%, #7c3aed 100%); padding: 60px 40px; text-align: center; }}
            .content {{ padding: 40px; }}
            .footer {{ padding: 30px 40px; text-align: center; background: rgba(255,255,255,0.02); border-top: 1px solid rgba(255,255,255,0.05); }}
            h1 {{ color: #ffffff; font-size: 28px; font-weight: 900; margin: 0; letter-spacing: -0.02em; }}
            p {{ color: #a1a1aa; font-size: 15px; line-height: 1.6; }}
            .btn {{ display: inline-block; padding: 14px 30px; background: #ffffff; color: #000000; text-decoration: none; border-radius: 12px; font-weight: 700; font-size: 14px; margin-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <div style="font-size: 10px; font-weight: 900; color: rgba(255,255,255,0.7); text-transform: uppercase; letter-spacing: 0.5em; margin-bottom: 20px;">InnerSync // AI Transmission</div>
                <h1>{title}</h1>
            </div>
            <div class="content">
                <p>{message}</p>
                {task_section}
                <div style="text-align: center;">
                    <a href="http://localhost:5173/dashboard" class="btn">Establish Re-Sync</a>
                </div>
            </div>
            <div class="footer">
                <p style="font-size: 11px; margin: 0;">&copy; 2026 InnerSync AI. This is a behavioral prompt generated by your Future Self engine.</p>
            </div>
        </div>
    </body>
    </html>
    """

async def send_goal_failure_email(to_email: str, goal_title: str):
    """
    Sends a high-end HTML email for goal expiration.
    """
    subject = f"Action Required: Your Goal '{goal_title}' has Expired"
    title = "Goal Decoupled"
    message = f"Unfortunately, the timeline for your goal \"{goal_title}\" has fractured. Your Future Self encourages you to re-establish resonance and try again."
    
    html_content = await _get_html_template(title, message)

    if not SMTP_USER or not SMTP_PASS:
        print(f"[MOCK EMAIL DISPATCHED] To: {to_email}")
        return

    try:
        def b_send():
            from email.mime.multipart import MIMEMultipart
            from email.mime.text import MIMEText
            
            msg = MIMEMultipart("alternative")
            msg['Subject'] = subject
            msg['From'] = f"InnerSync AI <{SMTP_USER}>"
            msg['To'] = to_email
            msg.attach(MIMEText(html_content, "html"))

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)

        await asyncio.to_thread(b_send)
    except Exception as e:
        print(f"Failed to send email: {e}")

async def send_task_reminder_email(to_email: str, goal_title: str, task_text: str):
    """
    Sends a high-end HTML email for task reminders.
    """
    subject = f"Friendly Reminder: Action needed for '{goal_title}'"
    title = "Timeline Alert"
    message = f"You have missed a critical step toward your goal \"{goal_title}\". Do not let the sync drift further."
    
    html_content = await _get_html_template(title, message, task_text)

    if not SMTP_USER or not SMTP_PASS:
        print(f"[MOCK TASK REMINDER DISPATCHED] To: {to_email}")
        return

    try:
        def b_send_rem():
            from email.mime.multipart import MIMEMultipart
            from email.mime.text import MIMEText
            
            msg = MIMEMultipart("alternative")
            msg['Subject'] = subject
            msg['From'] = f"InnerSync AI <{SMTP_USER}>"
            msg['To'] = to_email
            msg.attach(MIMEText(html_content, "html"))

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASS)
                server.send_message(msg)

        await asyncio.to_thread(b_send_rem)
    except Exception as e:
        print(f"Failed to send task reminder email: {e}")
